-- =====================================================================
-- Operational GPS modules: events, geofences, commands, reports, settings,
-- notification rules, fuel, billing and payments. Tables stay tenant-scoped.
-- =====================================================================

CREATE TABLE events (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id       BIGINT       NOT NULL,
    device_id       BIGINT       NOT NULL,
    vehicle_id      BIGINT       NULL,
    event_type      VARCHAR(48)  NOT NULL,
    severity        VARCHAR(16)  NOT NULL DEFAULT 'INFO',
    latitude        DOUBLE       NULL,
    longitude       DOUBLE       NULL,
    speed           DOUBLE       NULL,
    address         VARCHAR(512) NULL,
    device_time     DATETIME(6)  NULL,
    server_time     DATETIME(6)  NOT NULL,
    acknowledged    TINYINT(1)   NOT NULL DEFAULT 0,
    acknowledged_by BIGINT       NULL,
    acknowledged_at DATETIME(6)  NULL,
    detail          TEXT         NULL,
    created_at      DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_events_tenant_time (tenant_id, server_time),
    KEY idx_events_device_time (device_id, server_time),
    KEY idx_events_type_time (tenant_id, event_type, server_time),
    CONSTRAINT fk_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_events_device FOREIGN KEY (device_id) REFERENCES devices (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE geofences (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id           BIGINT       NOT NULL,
    name                VARCHAR(160) NOT NULL,
    description         VARCHAR(512) NULL,
    color               VARCHAR(9)   NOT NULL DEFAULT '#27D34D',
    type                VARCHAR(16)  NOT NULL,
    coordinates_json    TEXT         NOT NULL,
    radius_meters       DOUBLE       NULL,
    corridor_width_m    DOUBLE       NULL,
    assigned_device_ids TEXT         NULL,
    assigned_group_ids  TEXT         NULL,
    enter_alert         TINYINT(1)   NOT NULL DEFAULT 1,
    exit_alert          TINYINT(1)   NOT NULL DEFAULT 1,
    active_schedule     VARCHAR(256) NULL,
    active              TINYINT(1)   NOT NULL DEFAULT 1,
    created_at          DATETIME(6)  NOT NULL,
    updated_at          DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_geofences_tenant_active (tenant_id, active),
    CONSTRAINT fk_geofences_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification_rules (
    id                         BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id                  BIGINT       NOT NULL,
    name                       VARCHAR(160) NOT NULL,
    event_types                TEXT         NOT NULL,
    assigned_device_ids        TEXT         NULL,
    assigned_group_ids         TEXT         NULL,
    push_recipients            TEXT         NULL,
    email_recipients           TEXT         NULL,
    enabled                    TINYINT(1)   NOT NULL DEFAULT 1,
    active_schedule            VARCHAR(256) NULL,
    speed_threshold            DOUBLE       NULL,
    idle_threshold_minutes     INT          NULL,
    geofence_condition         VARCHAR(64)  NULL,
    repeat_suppression_minutes INT          NOT NULL DEFAULT 15,
    created_at                 DATETIME(6)  NOT NULL,
    updated_at                 DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_notification_rules_tenant (tenant_id, enabled),
    CONSTRAINT fk_notification_rules_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE device_commands (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id       BIGINT       NOT NULL,
    device_id       BIGINT       NOT NULL,
    command_type    VARCHAR(64)  NOT NULL,
    payload         TEXT         NULL,
    status          VARCHAR(24)  NOT NULL DEFAULT 'REQUESTED',
    requested_by    BIGINT       NOT NULL,
    idempotency_key VARCHAR(96)  NOT NULL,
    response_message VARCHAR(512) NULL,
    requested_at    DATETIME(6)  NOT NULL,
    updated_at      DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_commands_tenant_idempotency (tenant_id, idempotency_key),
    KEY idx_commands_device_time (device_id, requested_at),
    KEY idx_commands_status (tenant_id, status, requested_at),
    CONSTRAINT fk_commands_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_commands_device FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_commands_user FOREIGN KEY (requested_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE reports (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id       BIGINT       NOT NULL,
    requested_by    BIGINT       NOT NULL,
    report_type     VARCHAR(48)  NOT NULL,
    status          VARCHAR(24)  NOT NULL DEFAULT 'QUEUED',
    from_time       DATETIME(6)  NOT NULL,
    to_time         DATETIME(6)  NOT NULL,
    filters_json    TEXT         NULL,
    output_format   VARCHAR(16)  NOT NULL DEFAULT 'CSV',
    file_name       VARCHAR(256) NULL,
    file_size       BIGINT       NULL,
    download_url    VARCHAR(512) NULL,
    error_message   VARCHAR(512) NULL,
    created_at      DATETIME(6)  NOT NULL,
    completed_at    DATETIME(6)  NULL,
    PRIMARY KEY (id),
    KEY idx_reports_tenant_created (tenant_id, created_at),
    KEY idx_reports_status (tenant_id, status),
    CONSTRAINT fk_reports_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_reports_user FOREIGN KEY (requested_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE report_schedules (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id       BIGINT       NOT NULL,
    name            VARCHAR(160) NOT NULL,
    report_type     VARCHAR(48)  NOT NULL,
    cadence         VARCHAR(16)  NOT NULL,
    weekdays        VARCHAR(64)  NULL,
    execution_time  TIME         NOT NULL,
    timezone        VARCHAR(64)  NOT NULL,
    filters_json    TEXT         NULL,
    recipient_emails TEXT        NOT NULL,
    output_format   VARCHAR(16)  NOT NULL DEFAULT 'CSV',
    active          TINYINT(1)   NOT NULL DEFAULT 1,
    last_run_at     DATETIME(6)  NULL,
    next_run_at     DATETIME(6)  NULL,
    created_at      DATETIME(6)  NOT NULL,
    updated_at      DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_report_schedules_next_run (active, next_run_at),
    KEY idx_report_schedules_tenant (tenant_id),
    CONSTRAINT fk_report_schedules_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE fuel_readings (
    id             BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id      BIGINT       NOT NULL,
    vehicle_id     BIGINT       NOT NULL,
    device_id      BIGINT       NULL,
    position_id    BIGINT       NULL,
    reading_time   DATETIME(6)  NOT NULL,
    fuel_level     DOUBLE       NULL,
    fuel_added     DOUBLE       NULL,
    odometer       DOUBLE       NULL,
    cost           DECIMAL(12,2) NULL,
    note           VARCHAR(512) NULL,
    created_by     BIGINT       NULL,
    created_at     DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_fuel_vehicle_time (vehicle_id, reading_time),
    KEY idx_fuel_tenant_time (tenant_id, reading_time),
    CONSTRAINT fk_fuel_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_fuel_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_settings (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id             BIGINT       NOT NULL,
    user_id               BIGINT       NOT NULL,
    distance_unit         VARCHAR(8)   NOT NULL DEFAULT 'KM',
    speed_unit            VARCHAR(8)   NOT NULL DEFAULT 'KMH',
    time_format           VARCHAR(16)  NOT NULL DEFAULT '24H',
    map_style             VARCHAR(24)  NOT NULL DEFAULT 'street',
    traffic_enabled       TINYINT(1)   NOT NULL DEFAULT 0,
    route_color_mode      VARCHAR(24)  NOT NULL DEFAULT 'speed',
    notification_sound    TINYINT(1)   NOT NULL DEFAULT 1,
    language              VARCHAR(16)  NOT NULL DEFAULT 'en',
    date_format           VARCHAR(24)  NOT NULL DEFAULT 'dd-MMM-yyyy',
    default_history_range VARCHAR(24)  NOT NULL DEFAULT 'today',
    auto_follow_vehicle   TINYINT(1)   NOT NULL DEFAULT 1,
    refresh_frequency_sec INT          NOT NULL DEFAULT 30,
    privacy_options       TEXT         NULL,
    updated_at            DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_settings_user (tenant_id, user_id),
    CONSTRAINT fk_user_settings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE billing_transactions (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id       BIGINT       NOT NULL,
    device_id       BIGINT       NULL,
    type            VARCHAR(32)  NOT NULL,
    amount          DECIMAL(12,2) NOT NULL DEFAULT 0,
    points          DECIMAL(12,2) NULL,
    reference       VARCHAR(96)  NULL,
    status          VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    created_by      BIGINT       NULL,
    created_at      DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    KEY idx_billing_tenant_time (tenant_id, created_at),
    KEY idx_billing_reference (reference),
    CONSTRAINT fk_billing_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payments (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    tenant_id           BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL,
    provider            VARCHAR(32)  NOT NULL DEFAULT 'RAZORPAY',
    provider_order_id   VARCHAR(128) NOT NULL,
    provider_payment_id VARCHAR(128) NULL,
    amount              DECIMAL(12,2) NOT NULL,
    currency            VARCHAR(8)   NOT NULL DEFAULT 'INR',
    status              VARCHAR(24)  NOT NULL DEFAULT 'CREATED',
    idempotency_key     VARCHAR(96)  NOT NULL,
    failure_reason      VARCHAR(512) NULL,
    created_at          DATETIME(6)  NOT NULL,
    verified_at         DATETIME(6)  NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_payments_tenant_idempotency (tenant_id, idempotency_key),
    KEY idx_payments_reference (provider_order_id),
    CONSTRAINT fk_payments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
